import type {
  CommitRecord,
  AIDetectionResult,
  SuspiciousFile,
  AIToolId,
  AIConfidence,
} from '../../types/index.js';
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { existsSync } from 'node:fs';

interface AISignal {
  key: string;
  strength: 'strong' | 'medium' | 'weak';
  weight: number;
  dimension: string;
}

export interface AIScoreResult {
  rawScore: number;
  probability: number;
  confidence: AIConfidence;
  confidenceScore: number;
  minProbability: number;
  maxProbability: number;
  tools: AIToolId[];
  signals: AISignal[];
}

export function calculateAIScore(commit: CommitRecord): number {
  const result = analyzeAICommit(commit);
  return result.rawScore;
}

export function analyzeAICommit(commit: CommitRecord): AIScoreResult {
  const signals: AISignal[] = [];
  const totalDeleted = commit.files.reduce((sum, f) => sum + f.deleted, 0);
  const codeFiles = commit.files.filter(f => !isAutoGeneratedFile(f.path));
  const codeLines = codeFiles.reduce((sum, f) => sum + f.added, 0);

  if (codeLines === 0) {
    return {
      rawScore: 0,
      probability: 0,
      confidence: 'low',
      confidenceScore: 0,
      minProbability: 0,
      maxProbability: 0,
      tools: [],
      signals: [],
    };
  }

  // 强信号检测
  if (hasAICoAuthor(commit.message)) {
    signals.push({
      key: 'ai-coauthor',
      strength: 'strong',
      weight: 60,
      dimension: 'explicit-marker',
    });
  }

  if (hasExplicitGeneration(commit.message)) {
    signals.push({
      key: 'explicit-generation',
      strength: 'strong',
      weight: 55,
      dimension: 'explicit-marker',
    });
  }

  // 中信号检测
  if (hasAIToolSignature(commit.message)) {
    signals.push({
      key: 'ai-tool-signature',
      strength: 'medium',
      weight: 25,
      dimension: 'tool-feature',
    });
  }

  if (hasWebToolURL(commit.message)) {
    signals.push({
      key: 'web-tool-url',
      strength: 'medium',
      weight: 25,
      dimension: 'tool-feature',
    });
  }

  if (codeLines > 1000 && codeFiles.length > 10 && isGenericMessage(commit.message)) {
    signals.push({
      key: 'large-commit-generic',
      strength: 'medium',
      weight: 12,
      dimension: 'behavioral',
    });
  }

  // 弱信号检测
  if (codeLines > 300 && totalDeleted === 0 && codeFiles.length > 3) {
    signals.push({
      key: 'zero-delete-pattern',
      strength: 'weak',
      weight: 7,
      dimension: 'behavioral',
    });
  }

  const anomalousFiles = codeFiles.filter(f => hasAnomalousNaming(f.path));
  if (anomalousFiles.length > 0) {
    const weight = Math.min(6, (anomalousFiles.length / codeFiles.length) * 6);
    signals.push({
      key: 'anomalous-naming',
      strength: 'weak',
      weight,
      dimension: 'code-pattern',
    });
  }

  const rawScore = scoreSignals(signals);
  const probability = mapScoreToProbability(rawScore);
  const confidenceScore = calculateCommitConfidence(signals, codeLines);
  const confidence = toConfidenceLevel(confidenceScore);
  const delta = getProbabilityDelta(confidence);

  return {
    rawScore,
    probability,
    confidence,
    confidenceScore,
    minProbability: Math.max(0, probability - delta),
    maxProbability: Math.min(1, probability + delta),
    tools: detectAITools(commit.message),
    signals,
  };
}

function scoreSignals(signals: AISignal[]): number {
  const strongSum = Math.min(
    75,
    signals.filter(s => s.strength === 'strong').reduce((sum, s) => sum + s.weight, 0)
  );
  const mediumSum = Math.min(
    20,
    signals.filter(s => s.strength === 'medium').reduce((sum, s) => sum + s.weight, 0)
  );
  const weakSum = Math.min(
    10,
    signals.filter(s => s.strength === 'weak').reduce((sum, s) => sum + s.weight, 0)
  );

  const dimensions = new Set(signals.map(s => s.dimension)).size;
  const diversityBonus = Math.min(5, Math.max(0, dimensions - 1) * 2);

  return Math.min(100, strongSum + mediumSum + weakSum + diversityBonus);
}

function mapScoreToProbability(rawScore: number): number {
  if (rawScore <= 0) return 0;
  return 1 / (1 + Math.exp(-(rawScore - 50) / 8));
}

function calculateCommitConfidence(signals: AISignal[], commitLines: number): number {
  const strong = signals.filter(s => s.strength === 'strong').length;
  const medium = signals.filter(s => s.strength === 'medium').length;
  const dimensions = new Set(signals.map(s => s.dimension)).size;

  let score = 0.15;
  if (strong > 0) score += 0.4;
  score += Math.min(0.18, medium * 0.08);
  score += Math.min(0.15, Math.max(0, dimensions - 1) * 0.07);
  if (commitLines >= 150) score += 0.1;
  else if (commitLines < 30) score -= 0.08;
  if (strong === 0 && medium === 0) score -= 0.15;

  return Math.max(0, Math.min(1, score));
}

function toConfidenceLevel(score: number): AIConfidence {
  if (score >= 0.72) return 'high';
  if (score >= 0.45) return 'medium';
  return 'low';
}

function getProbabilityDelta(level: AIConfidence): number {
  if (level === 'high') return 0.08;
  if (level === 'medium') return 0.18;
  return 0.3;
}

const AI_CO_AUTHOR_PATTERNS = [
  /co-authored-by:.*copilot/i,
  /co-authored-by:.*\bcursor\b/i,
  /co-authored-by:.*claude/i,
  /co-authored-by:.*chatgpt/i,
  /co-authored-by:.*codeium/i,
  /co-authored-by:.*tabnine/i,
  /co-authored-by:.*devin/i,
  /co-authored-by:.*windsurf/i,
  /co-authored-by:.*aider/i,
];

function hasAICoAuthor(message: string): boolean {
  return AI_CO_AUTHOR_PATTERNS.some(p => p.test(message));
}

const EXPLICIT_GENERATION_PATTERNS = [
  /generated\s+by\s+ai/i,
  /ai\s+generated/i,
  /generated\s+with\s+\[/i,
  /auto-generated\s+by/i,
];

function hasExplicitGeneration(message: string): boolean {
  return EXPLICIT_GENERATION_PATTERNS.some(p => p.test(message));
}

const AI_TOOL_PATTERNS = [
  /\[ai\]/i,
  /\[copilot\]/i,
  /\[cursor\]/i,
  /🤖/,
  /\baider\b/i,
  /\bclaude\b.*\bgenerat/i,
  /\bchatgpt\b/i,
  /\bwindsurf\b/i,
];

function hasAIToolSignature(message: string): boolean {
  return AI_TOOL_PATTERNS.some(p => p.test(message));
}

const WEB_TOOL_PATTERNS = [
  /v0\.dev/i,
  /bolt\.new/i,
  /lovable\.dev/i,
  /replit\s+agent/i,
];

function hasWebToolURL(message: string): boolean {
  return WEB_TOOL_PATTERNS.some(p => p.test(message));
}

const AUTO_GENERATED_PATTERNS = [
  /package-lock\.json$/,
  /yarn\.lock$/,
  /pnpm-lock\.yaml$/,
  /\.lock$/,
  /\.min\.(js|css)$/,
  /\.generated\./,
  /\.snap$/,
  /dist\//,
  /build\//,
  /vendor\//,
  /node_modules\//,
];

export function isAutoGeneratedFile(path: string): boolean {
  return AUTO_GENERATED_PATTERNS.some(p => p.test(path));
}

/** 工具识别模式: [toolId, pattern[]] */
const TOOL_DETECTION_PATTERNS: [AIToolId, RegExp[]][] = [
  [
    'claude-code',
    [
      /claude\s*<noreply@anthropic\.com>/i,
      /generated\s+with\s+\[claude\s*code\]/i,
      /co-authored-by:.*claude/i,
    ],
  ],
  ['codex', [/\bcodex\b/i, /generated\s+with\s+codex/i]],
  ['opencode', [/\bopencode\b/i]],
  ['gemini', [/\bgemini\b/i, /generated\s+with\s+gemini/i]],
  ['cursor', [/\bcursor\b/i]],
  ['copilot', [/\bcopilot\b/i]],
  ['codeium', [/\bcodeium\b/i]],
  ['tabnine', [/\btabnine\b/i]],
  ['windsurf', [/\bwindsurf\b/i, /generated\s+with\s+windsurf/i, /co-authored-by:.*windsurf/i]],
  ['v0', [/\bv0(\\.dev)?\b/i, /generated\s+with\s+v0/i]],
  ['bolt', [/\bbolt(\\.new)?\b/i, /generated\s+with\s+bolt/i]],
  ['lovable', [/\blovable\b/i, /generated\s+with\s+lovable/i]],
  ['aider', [/\baider\b/i, /co-authored-by:.*aider/i]],
  ['cline', [/\bcline\b/i]],
  ['roo-code', [/\broo[- ]?code\b/i, /\broocode\b/i]],
  ['devin', [/\bdevin\b/i]],
];

/**
 * 从提交信息中识别 AI 工具
 * 支持 Co-authored-by 和 body 中的模式
 * @returns 去重后的工具 ID 数组
 */
export function detectAITools(message: string): AIToolId[] {
  const found = new Set<AIToolId>();

  for (const [toolId, patterns] of TOOL_DETECTION_PATTERNS) {
    if (patterns.some((p) => p.test(message))) {
      found.add(toolId);
    }
  }

  return Array.from(found);
}

export async function detectAICode(
  commits: CommitRecord[],
  repoPath: string
): Promise<AIDetectionResult> {
  const suspiciousFiles: SuspiciousFile[] = [];

  for (const commit of commits) {
    const totalLines = commit.files.reduce((sum, f) => sum + f.added, 0);

    if (totalLines > 1000 && commit.files.length > 10) {
      if (isGenericMessage(commit.message)) {
        suspiciousFiles.push({
          commit: commit.hash,
          reason: 'large-commit-generic-message',
          score: 80,
          description: `大型提交（${totalLines}行）配合通用提交信息`,
        });
      }
    }

    for (const file of commit.files) {
      if (hasAnomalousNaming(file.path)) {
        suspiciousFiles.push({
          file: file.path,
          reason: 'anomalous-naming',
          score: 60,
          description: '命名模式异常（如 function1, temp1）',
        });
      }
    }
  }

  const uniqueFiles = new Set(commits.flatMap(c => c.files.map(f => f.path)));
  const filesToCheck = Array.from(uniqueFiles).slice(0, 50);

  for (const filePath of filesToCheck) {
    const fullPath = join(repoPath, filePath);
    if (!existsSync(fullPath)) continue;

    try {
      const content = await readFile(fullPath, 'utf-8');
      const commentDensity = calculateCommentDensity(content);

      if (commentDensity > 0.3) {
        suspiciousFiles.push({
          file: filePath,
          reason: 'excessive-comments',
          score: 70,
          description: `注释密度过高（${(commentDensity * 100).toFixed(1)}%）`,
        });
      }
    } catch {
      // 忽略读取错误
    }
  }

  const uniqueSuspicious = Array.from(
    new Map(suspiciousFiles.map(f => [f.file || f.commit, f])).values()
  );

  return {
    suspiciousFiles: uniqueSuspicious.sort((a, b) => b.score - a.score).slice(0, 20),
    totalSuspicious: uniqueSuspicious.length,
  };
}

function isGenericMessage(message: string): boolean {
  const normalized = message.trim().split('\n')[0].trim();

  const exactPatterns = [
    /^fix$/i,
    /^update$/i,
    /^refactor$/i,
    /^fix bug$/i,
    /^update code$/i,
    /^bug fix$/i,
    /^minor fix$/i,
    /^wip$/i,
    /^temp$/i,
    /^test$/i,
    /^changes$/i,
    /^save$/i,
    /^commit$/i,
    /^\.$/,
    /^-$/,
    /^init$/i,
    /^initial commit$/i,
    /^first commit$/i,
    /^misc$/i,
    /^stuff$/i,
    /^no message$/i,
  ];

  if (exactPatterns.some(p => p.test(normalized))) return true;

  if (normalized.length <= 3) return true;

  const fuzzyPatterns = [
    /^update \w+$/i,
    /^fix \w+$/i,
    /^add \w+$/i,
    /^remove \w+$/i,
    /^delete \w+$/i,
    /^修复/,
    /^更新/,
    /^添加/,
    /^新增/,
  ];

  return normalized.length <= 15 && fuzzyPatterns.some(p => p.test(normalized));
}

function hasAnomalousNaming(path: string): boolean {
  const anomalousPatterns = [
    /function\d+/i,
    /temp\d+/i,
    /test\d+/i,
    /file\d+/i,
    /component\d+/i,
    /untitled/i,
    /copy\d*/i,
  ];

  return anomalousPatterns.some(pattern => pattern.test(path));
}

function calculateCommentDensity(content: string): number {
  const lines = content.split('\n');
  let commentLines = 0;
  let codeLines = 0;

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) continue;

    if (
      trimmed.startsWith('//') ||
      trimmed.startsWith('/*') ||
      trimmed.startsWith('*') ||
      trimmed.startsWith('#')
    ) {
      commentLines++;
    } else {
      codeLines++;
    }
  }

  const totalLines = commentLines + codeLines;
  return totalLines > 0 ? commentLines / totalLines : 0;
}
