import type {
  CommitRecord,
  AIDetectionResult,
  SuspiciousFile,
  AIToolId,
} from '../../types/index.js';
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { existsSync } from 'node:fs';

export function calculateAIScore(commit: CommitRecord): number {
  let score = 0;
  const totalLines = commit.files.reduce((sum, f) => sum + f.added, 0);
  const totalDeleted = commit.files.reduce((sum, f) => sum + f.deleted, 0);
  const codeFiles = commit.files.filter(f => !isAutoGeneratedFile(f.path));
  const codeLines = codeFiles.reduce((sum, f) => sum + f.added, 0);

  if (codeLines === 0) return 0;

  // 维度1: Co-authored-by AI 工具标记（强信号）
  if (hasAICoAuthor(commit.message)) {
    score += 50;
  }

  // 维度2: 提交消息包含 AI 工具特征
  if (hasAIToolSignature(commit.message)) {
    score += 35;
  }

  // 维度3: 大批量提交 + 通用消息（中等信号）
  if (codeLines > 1000 && codeFiles.length > 10 && isGenericMessage(commit.message)) {
    score += 25;
  } else if (codeLines > 800 && isGenericMessage(commit.message)) {
    score += 15;
  }

  // 维度4: 高新增零删除模式（AI 生成典型特征）
  if (codeLines > 300 && totalDeleted === 0 && codeFiles.length > 3) {
    score += 15;
  }

  // 维度5: 异常文件命名
  const anomalousFiles = codeFiles.filter(f => hasAnomalousNaming(f.path));
  if (anomalousFiles.length > 0) {
    score += Math.min(20, (anomalousFiles.length / codeFiles.length) * 20);
  }

  return Math.min(100, score);
}

const AI_CO_AUTHOR_PATTERNS = [
  /co-authored-by:.*copilot/i,
  /co-authored-by:.*\bcursor\b/i,
  /co-authored-by:.*\bai\b/i,
  /co-authored-by:.*\bbot\b/i,
  /co-authored-by:.*claude/i,
  /co-authored-by:.*chatgpt/i,
  /co-authored-by:.*openai/i,
  /co-authored-by:.*gemini/i,
  /co-authored-by:.*codeium/i,
  /co-authored-by:.*tabnine/i,
  /co-authored-by:.*devin/i,
];

function hasAICoAuthor(message: string): boolean {
  return AI_CO_AUTHOR_PATTERNS.some(p => p.test(message));
}

const AI_TOOL_PATTERNS = [
  /generated by/i,
  /auto[- ]?generated/i,
  /\[ai\]/i,
  /\[copilot\]/i,
  /\[cursor\]/i,
  /🤖/,
  /\baider\b/i,
  /\bclaude\b.*\bgenerat/i,
  /\bchatgpt\b/i,
];

function hasAIToolSignature(message: string): boolean {
  return AI_TOOL_PATTERNS.some(p => p.test(message));
}

const AUTO_GENERATED_PATTERNS = [
  /package-lock\.json$/,
  /yarn\.lock$/,
  /pnpm-lock\.yaml$/,
  /\.lock$/,
  /\.min\.(js|css)$/,
  /\.generated\./,
  /\.snap$/,
  /dist\//,
  /build\//,
  /vendor\//,
  /node_modules\//,
];

export function isAutoGeneratedFile(path: string): boolean {
  return AUTO_GENERATED_PATTERNS.some(p => p.test(path));
}

/** 工具识别模式: [toolId, pattern[]] */
const TOOL_DETECTION_PATTERNS: [AIToolId, RegExp[]][] = [
  [
    'claude-code',
    [
      /claude\s*<noreply@anthropic\.com>/i,
      /generated\s+with\s+\[claude\s*code\]/i,
      /co-authored-by:.*claude/i,
    ],
  ],
  ['codex', [/codex/i, /openai/i]],
  ['opencode', [/\bopencode\b/i]],
  ['gemini', [/\bgemini\b/i, /\bgoogle\b/i]],
  ['cursor', [/\bcursor\b/i]],
  ['copilot', [/\bcopilot\b/i]],
  ['codeium', [/\bcodeium\b/i]],
  ['tabnine', [/\btabnine\b/i]],
];

/**
 * 从提交信息中识别 AI 工具
 * 支持 Co-authored-by 和 body 中的模式
 * @returns 去重后的工具 ID 数组
 */
export function detectAITools(message: string): AIToolId[] {
  const found = new Set<AIToolId>();

  for (const [toolId, patterns] of TOOL_DETECTION_PATTERNS) {
    if (patterns.some((p) => p.test(message))) {
      found.add(toolId);
    }
  }

  return Array.from(found);
}

export async function detectAICode(
  commits: CommitRecord[],
  repoPath: string
): Promise<AIDetectionResult> {
  const suspiciousFiles: SuspiciousFile[] = [];

  for (const commit of commits) {
    const totalLines = commit.files.reduce((sum, f) => sum + f.added, 0);

    if (totalLines > 1000 && commit.files.length > 10) {
      if (isGenericMessage(commit.message)) {
        suspiciousFiles.push({
          commit: commit.hash,
          reason: 'large-commit-generic-message',
          score: 80,
          description: `大型提交（${totalLines}行）配合通用提交信息`,
        });
      }
    }

    for (const file of commit.files) {
      if (hasAnomalousNaming(file.path)) {
        suspiciousFiles.push({
          file: file.path,
          reason: 'anomalous-naming',
          score: 60,
          description: '命名模式异常（如 function1, temp1）',
        });
      }
    }
  }

  const uniqueFiles = new Set(commits.flatMap(c => c.files.map(f => f.path)));
  const filesToCheck = Array.from(uniqueFiles).slice(0, 50);

  for (const filePath of filesToCheck) {
    const fullPath = join(repoPath, filePath);
    if (!existsSync(fullPath)) continue;

    try {
      const content = await readFile(fullPath, 'utf-8');
      const commentDensity = calculateCommentDensity(content);

      if (commentDensity > 0.3) {
        suspiciousFiles.push({
          file: filePath,
          reason: 'excessive-comments',
          score: 70,
          description: `注释密度过高（${(commentDensity * 100).toFixed(1)}%）`,
        });
      }
    } catch {
      // 忽略读取错误
    }
  }

  const uniqueSuspicious = Array.from(
    new Map(suspiciousFiles.map(f => [f.file || f.commit, f])).values()
  );

  return {
    suspiciousFiles: uniqueSuspicious.sort((a, b) => b.score - a.score).slice(0, 20),
    totalSuspicious: uniqueSuspicious.length,
  };
}

function isGenericMessage(message: string): boolean {
  const normalized = message.trim().split('\n')[0].trim();

  const exactPatterns = [
    /^fix$/i,
    /^update$/i,
    /^refactor$/i,
    /^fix bug$/i,
    /^update code$/i,
    /^bug fix$/i,
    /^minor fix$/i,
    /^wip$/i,
    /^temp$/i,
    /^test$/i,
    /^changes$/i,
    /^save$/i,
    /^commit$/i,
    /^\.$/,
    /^-$/,
    /^init$/i,
    /^initial commit$/i,
    /^first commit$/i,
    /^misc$/i,
    /^stuff$/i,
    /^no message$/i,
  ];

  if (exactPatterns.some(p => p.test(normalized))) return true;

  if (normalized.length <= 3) return true;

  const fuzzyPatterns = [
    /^update \w+$/i,
    /^fix \w+$/i,
    /^add \w+$/i,
    /^remove \w+$/i,
    /^delete \w+$/i,
    /^修复/,
    /^更新/,
    /^添加/,
    /^新增/,
  ];

  return normalized.length <= 15 && fuzzyPatterns.some(p => p.test(normalized));
}

function hasAnomalousNaming(path: string): boolean {
  const anomalousPatterns = [
    /function\d+/i,
    /temp\d+/i,
    /test\d+/i,
    /file\d+/i,
    /component\d+/i,
    /untitled/i,
    /copy\d*/i,
  ];

  return anomalousPatterns.some(pattern => pattern.test(path));
}

function calculateCommentDensity(content: string): number {
  const lines = content.split('\n');
  let commentLines = 0;
  let codeLines = 0;

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) continue;

    if (
      trimmed.startsWith('//') ||
      trimmed.startsWith('/*') ||
      trimmed.startsWith('*') ||
      trimmed.startsWith('#')
    ) {
      commentLines++;
    } else {
      codeLines++;
    }
  }

  const totalLines = commentLines + codeLines;
  return totalLines > 0 ? commentLines / totalLines : 0;
}
