import type {
  CommitRecord,
  AIMetrics,
  AICommit,
  AuthorAIStats,
  DirectoryAIStats,
  AITrendPoint,
  ToolAIMetrics,
  ToolAITrendPoint,
  AuthorToolAIStats,
  DirectoryToolAIStats,
  AIToolId,
  AIConfidence,
} from '../types/index.js';
import {
  analyzeAICommit,
  isAutoGeneratedFile,
  detectAITools,
} from './tech-debt/ai-detector.js';
import { getISOWeekKey } from '../utils/date-utils.js';

export function calculateAIMetrics(commits: CommitRecord[]): {
  aiMetrics: AIMetrics;
  authorAIStats: AuthorAIStats[];
  directoryAIStats: DirectoryAIStats[];
  aiTrends: AITrendPoint[];
  toolAIMetrics: ToolAIMetrics[];
  toolAITrends: ToolAITrendPoint[];
  authorToolAIStats: AuthorToolAIStats[];
  directoryToolAIStats: DirectoryToolAIStats[];
} {
  if (commits.length === 0) {
    return {
      aiMetrics: {
        totalAILines: 0,
        totalLines: 0,
        aiPercentage: 0,
        confidence: 'low',
        confidenceScore: 0,
        estimatedRange: { minLines: 0, maxLines: 0, minPercentage: 0, maxPercentage: 0 },
        suspiciousCommits: 0,
        highAICommits: [],
      },
      authorAIStats: [],
      directoryAIStats: [],
      aiTrends: [],
      toolAIMetrics: [],
      toolAITrends: [],
      authorToolAIStats: [],
      directoryToolAIStats: [],
    };
  }

  const aiCommits: AICommit[] = [];
  const authorAIMap = new Map<string, { aiLines: number; totalLines: number }>();
  const directoryAIMap = new Map<string, { aiLines: number; totalLines: number; commits: Set<string>; lastModified: Date }>();
  const weeklyAIMap = new Map<string, { aiLines: number; totalLines: number }>();
  const toolMetricsMap = new Map<AIToolId, { totalLines: number; aiLines: number; commits: number }>();
  const toolTrendsMap = new Map<string, { aiLines: number; totalLines: number }>();
  const authorToolMap = new Map<string, { aiLines: number; totalLines: number }>();
  const dirToolMap = new Map<string, { aiLines: number; totalLines: number; commits: Set<string> }>();

  let totalAILines = 0;
  let totalLines = 0;
  let totalMinAILines = 0;
  let totalMaxAILines = 0;
  let suspiciousCommits = 0;
  let confidenceWeightedSum = 0;

  for (const commit of commits) {
    const result = analyzeAICommit(commit);
    const tools = result.tools;
    const effectiveTools: AIToolId[] =
      tools.length > 0 ? tools : result.probability > 0 ? ['other'] : [];

    const codeFiles = commit.files.filter(f => !isAutoGeneratedFile(f.path));
    const commitLines = codeFiles.reduce((sum, f) => sum + f.added, 0);
    const estimatedAILines = commitLines * result.probability;
    const minAILines = commitLines * result.minProbability;
    const maxAILines = commitLines * result.maxProbability;

    totalLines += commitLines;
    totalAILines += estimatedAILines;
    totalMinAILines += minAILines;
    totalMaxAILines += maxAILines;

    const confidenceWeight = result.confidence === 'high' ? 3 : result.confidence === 'medium' ? 2 : 1;
    confidenceWeightedSum += confidenceWeight * commitLines;

    if (result.probability >= 0.75 || (result.probability >= 0.6 && result.confidence === 'high')) {
      suspiciousCommits++;
      aiCommits.push({
        hash: commit.hash,
        author: commit.author,
        date: commit.date,
        aiScore: result.rawScore,
        confidence: result.confidence,
        linesAdded: commitLines,
        filesCount: codeFiles.length,
        message: commit.message,
      });
    }

    for (const toolId of effectiveTools) {
      const m = toolMetricsMap.get(toolId) || {
        totalLines: 0,
        aiLines: 0,
        commits: 0,
      };
      m.totalLines += commitLines;
      m.aiLines += estimatedAILines;
      m.commits += 1;
      toolMetricsMap.set(toolId, m);

      const week = getISOWeekKey(commit.date);
      const trendKey = `${week}-${toolId}`;
      const t = toolTrendsMap.get(trendKey) || { aiLines: 0, totalLines: 0 };
      t.aiLines += estimatedAILines;
      t.totalLines += commitLines;
      toolTrendsMap.set(trendKey, t);

      const authorToolKey = `${commit.email.toLowerCase()}|||${toolId}`;
      const at = authorToolMap.get(authorToolKey) || { aiLines: 0, totalLines: 0 };
      at.aiLines += estimatedAILines;
      at.totalLines += commitLines;
      authorToolMap.set(authorToolKey, at);

      for (const file of codeFiles) {
        const dir = getTopDirectory(file.path);
        const fileAILines = file.added * result.probability;
        const dirToolKey = `${dir}|||${toolId}`;
        const dt = dirToolMap.get(dirToolKey) || {
          aiLines: 0,
          totalLines: 0,
          commits: new Set<string>(),
        };
        dt.aiLines += fileAILines;
        dt.totalLines += file.added;
        dt.commits.add(commit.hash);
        dirToolMap.set(dirToolKey, dt);
      }
    }

    const authorKey = commit.email.toLowerCase();
    const authorData = authorAIMap.get(authorKey) || { aiLines: 0, totalLines: 0 };
    authorData.aiLines += estimatedAILines;
    authorData.totalLines += commitLines;
    authorAIMap.set(authorKey, authorData);

    for (const file of codeFiles) {
      const dir = getTopDirectory(file.path);
      const fileAILines = file.added * result.probability;

      const dirData = directoryAIMap.get(dir) || {
        aiLines: 0,
        totalLines: 0,
        commits: new Set(),
        lastModified: commit.date,
      };
      dirData.aiLines += fileAILines;
      dirData.totalLines += file.added;
      dirData.commits.add(commit.hash);
      if (commit.date > dirData.lastModified) {
        dirData.lastModified = commit.date;
      }
      directoryAIMap.set(dir, dirData);
    }

    const week = getISOWeekKey(commit.date);
    const weekData = weeklyAIMap.get(week) || { aiLines: 0, totalLines: 0 };
    weekData.aiLines += estimatedAILines;
    weekData.totalLines += commitLines;
    weeklyAIMap.set(week, weekData);
  }

  const avgConfidenceWeight = totalLines > 0 ? confidenceWeightedSum / totalLines : 0;
  const overallConfidence: AIConfidence =
    avgConfidenceWeight >= 2.5 ? 'high' : avgConfidenceWeight >= 1.5 ? 'medium' : 'low';

  const basePercentage = totalLines > 0 ? (totalAILines / totalLines) * 100 : 0;
  const minPercentage = totalLines > 0 ? (totalMinAILines / totalLines) * 100 : 0;
  const maxPercentage = totalLines > 0 ? (totalMaxAILines / totalLines) * 100 : 0;

  const aiMetrics: AIMetrics = {
    totalAILines: Math.round(totalAILines),
    totalLines,
    aiPercentage: basePercentage,
    confidence: overallConfidence,
    confidenceScore: avgConfidenceWeight / 3,
    estimatedRange: {
      minLines: Math.round(totalMinAILines),
      maxLines: Math.round(totalMaxAILines),
      minPercentage,
      maxPercentage,
    },
    suspiciousCommits,
    highAICommits: aiCommits.sort((a, b) => b.aiScore - a.aiScore).slice(0, 20),
  };

  const authorAIStats: AuthorAIStats[] = [];
  const authorMap = new Map<string, { name: string; email: string }>();
  for (const commit of commits) {
    authorMap.set(commit.email.toLowerCase(), { name: commit.author, email: commit.email });
  }

  const authorToolAIStats: AuthorToolAIStats[] = Array.from(authorToolMap.entries())
    .map(([key, data]) => {
      const [email, toolId] = key.split('|||');
      const author = authorMap.get(email);
      return author
        ? {
            author: author.name,
            email: author.email,
            toolId: toolId as AIToolId,
            aiLines: Math.round(data.aiLines),
            totalLines: data.totalLines,
            aiPercentage: data.totalLines > 0 ? (data.aiLines / data.totalLines) * 100 : 0,
          }
        : null;
    })
    .filter((x): x is AuthorToolAIStats => x !== null)
    .sort((a, b) => b.aiLines - a.aiLines);

  const directoryToolAIStats: DirectoryToolAIStats[] = Array.from(dirToolMap.entries())
    .map(([key, data]) => {
      const [path, toolId] = key.split('|||');
      return {
        path,
        toolId: toolId as AIToolId,
        aiLines: Math.round(data.aiLines),
        totalLines: data.totalLines,
        commits: data.commits.size,
        aiPercentage: data.totalLines > 0 ? (data.aiLines / data.totalLines) * 100 : 0,
      };
    })
    .sort((a, b) => b.aiLines - a.aiLines);

  for (const [authorKey, data] of authorAIMap) {
    const author = authorMap.get(authorKey);
    if (author) {
      authorAIStats.push({
        author: author.name,
        email: author.email,
        aiLines: Math.round(data.aiLines),
        totalLines: data.totalLines,
        aiPercentage: data.totalLines > 0 ? (data.aiLines / data.totalLines) * 100 : 0,
      });
    }
  }

  const directoryAIStats: DirectoryAIStats[] = [];
  for (const [path, data] of directoryAIMap) {
    const aiPercentage = data.totalLines > 0 ? (data.aiLines / data.totalLines) * 100 : 0;
    const isHighRisk = data.commits.size > 50 && aiPercentage > 60;

    directoryAIStats.push({
      path,
      commits: data.commits.size,
      aiLines: Math.round(data.aiLines),
      totalLines: data.totalLines,
      aiPercentage,
      lastModified: data.lastModified,
      isHighRisk,
    });
  }

  const aiTrends: AITrendPoint[] = Array.from(weeklyAIMap.entries())
    .map(([week, data]) => ({
      week,
      aiLines: Math.round(data.aiLines),
      totalLines: data.totalLines,
      aiPercentage: data.totalLines > 0 ? (data.aiLines / data.totalLines) * 100 : 0,
    }))
    .sort((a, b) => a.week.localeCompare(b.week));

  const toolAIMetrics: ToolAIMetrics[] = Array.from(toolMetricsMap.entries())
    .map(([toolId, data]) => ({
      toolId,
      totalLines: data.totalLines,
      aiLines: Math.round(data.aiLines),
      commits: data.commits,
      aiPercentage: data.totalLines > 0 ? (data.aiLines / data.totalLines) * 100 : 0,
    }))
    .sort((a, b) => b.aiLines - a.aiLines);

  const toolAITrends: ToolAITrendPoint[] = Array.from(toolTrendsMap.entries())
    .map(([key, data]) => {
      const parts = key.split('-');
      const week = parts.length >= 2 ? `${parts[0]}-${parts[1]}` : key;
      const toolId = parts.length > 2 ? parts.slice(2).join('-') : 'other';
      return {
        week,
        toolId: toolId as AIToolId,
        aiLines: Math.round(data.aiLines),
        totalLines: data.totalLines,
        aiPercentage: data.totalLines > 0 ? (data.aiLines / data.totalLines) * 100 : 0,
      };
    })
    .sort((a, b) => a.week.localeCompare(b.week) || a.toolId.localeCompare(b.toolId));

  return {
    aiMetrics,
    authorAIStats: authorAIStats.sort((a, b) => b.aiPercentage - a.aiPercentage),
    directoryAIStats: directoryAIStats.sort((a, b) => b.aiPercentage - a.aiPercentage),
    aiTrends,
    toolAIMetrics,
    toolAITrends,
    authorToolAIStats,
    directoryToolAIStats,
  };
}

function getTopDirectory(filePath: string): string {
  const parts = filePath.split('/');
  return parts.length > 1 ? parts[0] : '(根目录)';
}
